name: CI

on:
  push:

jobs:
  terraform:
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply
        run: terraform apply

